Jhoseph
PyDayCochabamba/PyDay-2024 pull request #16
Opened 2024-04-20 20:16 UTC by Jhosephcaceres19

2024-04-20 20:43 UTC, CarittoDev approved these changes

2024-04-20 23:45 UTC, AlvaroViamont requested changes
Corregir indentación en HTML y CSS

Linea 4: manejar el {%load%} en una linea separada del {%block%}

2024-04-21 15:45 UTC, jessicaori requested changes
Añadir extensión Prettier para evitar cambios en la identación de código.

2024-04-21 21:25 UTC, Jhosephcaceres19 commented
footer

2024-04-21 21:27 UTC, closed without merging